'use client';

import { useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { DynamicLayout } from '@/components/DynamicLayout';
import { SkeletonLoader } from '@/components/SkeletonLoader';
import { useLayoutContext } from '@/context/LayoutContext';
import { CONTENT } from '@/lib/dictionary';

export default function Home() {
  const { layout, loading, isGenerating } = useLayoutContext();
  const contentRef = useRef<HTMLDivElement>(null);

  // Auto-scroll when layout is populated and not initial loading
  useEffect(() => {
    if (layout && !loading && !isGenerating && contentRef.current) {
      // Small timeout to ensure DOM render
      setTimeout(() => {
        contentRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 500);
    }
  }, [layout, loading, isGenerating]);

  // If loading and NO layout, show full screen skeleton. 
  // If we have a layout but are regenerating, we might want to just show the spinner in the input (handled by GlobalInput)
  if (loading && !layout) {
    return <SkeletonLoader />;
  }

  if (!layout) {
    return <div className="text-center p-10">Failed to load content.</div>;
  }

  // Handle "Finished but Empty"
  if (!loading && !isGenerating && layout.layout?.length === 0) {
    return <div className="text-center p-10 text-slate-500">No content generated. Try again?</div>;
  }

  return (
    <main className="relative">
      <motion.div
        ref={contentRef}
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="pt-20"
      >
        <DynamicLayout layout={layout} />

        {/* AI Disclaimer */}
        <div className="text-center p-4 pb-8 opacity-60 hover:opacity-100 transition-opacity">
          <p className="text-xs text-slate-500">
            {CONTENT.global.downloadCV ? ( /* Fallback safe check or direct usage */
              <>
                {CONTENT.generative.aiDisclaimer}
                <a href="/resume/johnpino_resume.pdf" target="_blank" className="underline hover:text-accent-pink transition-colors" download>
                  {CONTENT.generative.aiDisclaimerLink}
                </a>
              </>
            ) : (
              "Content generated by AI."
            )}
          </p>
        </div>
      </motion.div>
    </main>
  );
}
